services:
  app-rule-engine:
    build: 
      context: .
    ports:
      - "8081:6969"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zeotapdb
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4:latest  
    container_name: pgadmin  
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  
    ports:
      - "80:80"  
    networks:
      - zeotapnetwork  
volumes:
  pgdata:
networks:
  zeotapnetwork:
